import { test } from 'node:test'
import assert from 'node:assert/strict'
import { execFileSync } from 'node:child_process'
import { mkdtempSync, mkdirSync, writeFileSync, readFileSync, rmSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join, dirname } from 'node:path'
import { inflateRawSync } from 'node:zlib'
import { createRegistry, createPrng } from '../../core/src/index.js'
import {
  packComponent, readBundle, componentScript, manifestOfBundle, requireBundle, validateManifest, checkIcon,
  normalizeFiles, packUpload, readZip, BUNDLE_FORMAT, jsonErrorOffset
} from '../src/index.js'
import { messageQueueFolder, loadModules, makeZip } from './fixtures.js'

const messages = problems => problems.map(p => `${p.level} ${p.file}: ${p.message}`)
const shuffled = obj => Object.fromEntries(Object.entries(obj).reverse())

test('packing the spec’s message queue folder', () => {
  const result = packComponent(messageQueueFolder(), { name: 'message-queue' })
  assert.deepEqual(result.problems.filter(p => p.level === 'error'), [])
  const { bundle } = result
  assert.ok(bundle)
  assert.equal(bundle.format, BUNDLE_FORMAT)
  assert.equal(result.fileName, 'message-queue.strata.js')
  assert.equal(bundle.manifest.id, 'acme.message-queue')
  assert.match(bundle.icon ?? '', /^<svg/)
  assert.deepEqual(Object.keys(bundle.modules).sort(), ['index.js', 'lib/backoff.js', 'lib/defaults.json'])
  assert.deepEqual(Object.keys(bundle.assets).sort(), ['README.md', 'templates/runbook.md'], 'self-tests, dotfiles and unused modules stay out')
  assert.equal(bundle.entry, 'index.js')
  assert.match(bundle.integrity, /^sha256-[A-Za-z0-9+/]{43}=$/)
  assert.deepEqual(messages(result.problems), ['warning lib/unused.js: Not imported by the entry or a migration, so it is left out of the bundle'])
  assert.match(result.script ?? '', /^\/\/ message-queue\.strata\.js \(generated by strata pack; do not edit\)\n\/\/ acme\.message-queue@1\.2\.0 · sha256-/)
  assert.match(result.script ?? '', /\nStrata\.registerComponent\(\{/)
})

test('packing is deterministic: the same folder gives the same bytes in any file order', () => {
  const a = packComponent(messageQueueFolder())
  const b = packComponent(shuffled(messageQueueFolder()))
  assert.equal(a.script, b.script)
  const changed = { ...messageQueueFolder(), 'lib/backoff.js': 'export function backoff () { return 1 }\n' }
  assert.notEqual(packComponent(changed).bundle?.integrity, a.bundle?.integrity)
})

test('the packed behaviour runs: modules load through the runtime, as in the worker', () => {
  const { bundle } = packComponent(messageQueueFolder())
  assert.ok(bundle)
  const behaviour = loadModules(bundle.modules, bundle.entry ?? '').default
  const sent = []
  const ctx = {
    state: {},
    props: { capacity: 2 },
    now: 0,
    metric () {},
    schedule: (delay, name) => sent.push(['schedule', delay, name]),
    reject: (msg, code) => sent.push(['reject', msg, code]),
    send: (port, msg) => sent.push(['send', port, msg])
  }
  behaviour.init(ctx)
  behaviour.onMessage('m1', ctx)
  behaviour.onMessage('m2', ctx)
  behaviour.onMessage('m3', ctx)
  behaviour.onTimer('deliver', ctx)
  assert.deepEqual(sent, [['schedule', 10, 'deliver'], ['schedule', 20, 'deliver'], ['reject', 'm3', 'QUEUE_FULL'], ['send', 'out', 'm1']])
})

test('a .strata.js reads back without evaluation and its integrity is checked', () => {
  const { bundle, script } = packComponent(messageQueueFolder())
  assert.ok(bundle && script)
  assert.deepEqual(readBundle(script), bundle)
  assert.deepEqual(readBundle(JSON.stringify(bundle)), bundle)
  assert.deepEqual(readBundle(structuredClone(bundle)), bundle)

  const tampered = script.replace('Math.min(base', 'Math.max(base')
  assert.notEqual(tampered, script)
  assert.throws(() => readBundle(tampered), /changed after it was packed \(integrity mismatch\)\. Pack it again/)
  assert.throws(() => readBundle('console.log("hi")'), /not a packed component/)
  assert.throws(() => readBundle({ ...bundle, modules: { 'index.js': 5 } }), /modules must map paths to text/)
  assert.throws(() => readBundle({ ...bundle, entry: 'missing.js' }), /entry 'missing.js' is not among the modules/)
})

test('a packed bundle registers like any manifest, with its icon', () => {
  const { bundle } = packComponent(messageQueueFolder())
  assert.ok(bundle)
  const registry = createRegistry()
  registry.register(manifestOfBundle(bundle))
  const eff = registry.resolve('acme.message-queue')
  assert.equal(eff?.typeRef, 'acme.message-queue@1.2.0')
  assert.match(eff?.iconSvg ?? '', /^<svg/)
  assert.deepEqual(eff?.lineage, ['acme.message-queue', 'base:queue', 'base:component'])
  assert.equal(registry.find('message-queue')?.id, 'acme.message-queue')
})

test('manifest validation reports every problem with a way forward', () => {
  const problems = validateManifest({
    id: 'base:mine',
    name: 'Mine',
    version: '1.0',
    kind: 'widget',
    entyr: 'index.js',
    ports: [{ name: 'in', direction: 'sideways' }],
    properties: {
      latency: { type: 'number', default: 5 },
      mode: { type: 'enum', values: [] }
    },
    icon: 'icn.svg'
  }, { files: ['manifest.json', 'icon.svg'] })
  const text = messages(problems).join('\n')
  for (const expected of [
    /error .*version must be a semantic version/,
    /error .*ports\[0\]\.direction must be in, out or both/,
    /error .*properties\.mode\.values must list the enum options/,
    /error .*strataApi is required/,
    /error .*'base:' are reserved/,
    /error .*kind must be one of component, connection-type/,
    /warning .*Unknown key 'entyr'\. Did you mean 'entry'\?/,
    /warning .*properties\.latency: a number needs an explicit unit/,
    /error .*icon 'icn\.svg' is not in the folder\. Did you mean 'icon\.svg'\?/
  ]) assert.match(text, expected)

  assert.match(messages(validateManifest({ strataApi: '^1.0', id: 'acme.http', name: 'HTTP', version: '1.0.0', kind: 'connection-type', ports: [{ name: 'x', direction: 'in' }] })).join(), /a connection type has no ports/)
  assert.match(messages(validateManifest({ strataApi: '^1.0', id: 'thing', name: 'Thing', version: '1.0.0' })).join(), /has no namespace.*neither "extends" nor "entry"/s)
  assert.match(messages(validateManifest({ strataApi: '^9.0', id: 'acme.x', name: 'X', version: '1.0.0', extends: 'base:service' })).join(), /not compatible with this core/)
  assert.deepEqual(validateManifest(JSON.parse(messageQueueFolder()['manifest.json']), { files: Object.keys(messageQueueFolder()) }), [])
})

test('packing stops at errors and says where they are', () => {
  const broken = { ...messageQueueFolder(), 'manifest.json': '{\n  "id": "acme.q",\n  "name": oops\n}' }
  const r = packComponent(broken)
  assert.equal(r.bundle, null)
  assert.match(messages(r.problems)[0], /^error manifest\.json: Invalid JSON \(line 3, column 11\): /)

  const badModule = { ...messageQueueFolder(), 'lib/backoff.js': 'export function backoff () {\n  return "oops\n}' }
  const r2 = packComponent(badModule)
  assert.equal(r2.bundle, null)
  assert.deepEqual(r2.problems.filter(p => p.level === 'error').map(p => [p.file, p.line]), [['lib/backoff.js', 2]])
  assert.throws(() => requireBundle(r2), /could not be packed:\nlib\/backoff\.js:2: error: Unterminated string/)

  assert.match(messages(packComponent({}).problems)[0], /The folder is empty/)
  assert.match(messages(packComponent({ 'README.md': 'hi' }).problems)[0], /No manifest\.json/)
  const badIcon = { ...messageQueueFolder(), 'icon.svg': '<html></html>' }
  assert.match(messages(packComponent(badIcon).problems).join(), /The icon is not an SVG document/)
})

test('icons: scripts, handlers and external links are flagged', () => {
  const text = messages(checkIcon('<svg><script>alert(1)</script><rect onclick="x()"/><image href="https://x/y.png"/></svg>')).join('\n')
  assert.match(text, /script, which will be removed/)
  assert.match(text, /event handler attributes/)
  assert.match(text, /external resources/)
  assert.match(text, /no viewBox/)
})

test('uploads: a .strata.js, a zip, or the files of a folder', async () => {
  const { bundle, script } = packComponent(messageQueueFolder(), { name: 'message-queue' })
  assert.ok(bundle && script)

  const fromScript = await packUpload([{ path: 'message-queue.strata.js', content: new TextEncoder().encode(script) }])
  assert.deepEqual(fromScript.bundle, bundle)
  assert.equal(fromScript.fileName, 'message-queue.strata.js')

  const folder = Object.fromEntries(Object.entries(messageQueueFolder()).map(([p, c]) => [`message-queue/${p}`, c]))
  const zipped = makeZip(folder)
  const fromZip = await packUpload([{ path: 'message-queue.zip', content: zipped }])
  assert.equal(fromZip.bundle?.integrity, bundle.integrity, 'the zip packs to the same bundle as the folder')
  assert.equal(fromZip.fileName, 'message-queue.strata.js')

  const viaZlib = await packUpload([{ path: 'q.zip', content: makeZip(folder, { deflate: false }) }], { inflateRaw: data => new Uint8Array(inflateRawSync(data)) })
  assert.equal(viaZlib.bundle?.integrity, bundle.integrity, 'stored entries and an injected inflater')

  const fromFolder = await packUpload(Object.entries(folder).map(([path, content]) => ({ path, content })))
  assert.equal(fromFolder.bundle?.integrity, bundle.integrity)
  assert.equal(fromFolder.fileName, 'message-queue.strata.js')

  const tampered = await packUpload([{ path: 'x.strata.js', content: script.replace('Buffers', 'Loses') }])
  assert.equal(tampered.bundle, null)
  assert.match(tampered.problems[0].message, /integrity mismatch/)
  const notZip = await packUpload([{ path: 'x.zip', content: new Uint8Array([1, 2, 3]) }])
  assert.match(notZip.problems[0].message, /Not a readable zip file/)
})

test('zip archives made by the zip tool read back exactly', async t => {
  let dir
  try {
    execFileSync('zip', ['-v'], { stdio: 'ignore' })
  } catch {
    t.skip('zip is not installed')
    return
  }
  try {
    dir = mkdtempSync(join(tmpdir(), 'strata-zip-'))
    const files = messageQueueFolder()
    for (const [path, content] of Object.entries(files)) {
      mkdirSync(dirname(join(dir, 'message-queue', path)), { recursive: true })
      writeFileSync(join(dir, 'message-queue', path), content)
    }
    execFileSync('zip', ['-qr', 'q.zip', 'message-queue'], { cwd: dir })
    const entries = await readZip(new Uint8Array(readFileSync(join(dir, 'q.zip'))))
    const normalized = normalizeFiles(entries)
    assert.deepEqual(Object.keys(normalized).sort(), Object.keys(files).sort())
    assert.equal(new TextDecoder().decode(normalized['index.js']), files['index.js'])
    const encrypted = makeZip({ 'a.txt': 'x' }, { flags: 1 })
    await assert.rejects(readZip(encrypted), /encrypted/)
  } finally {
    if (dir) rmSync(dir, { recursive: true, force: true })
  }
})

test('componentScript and readBundle agree for any bundle', () => {
  const { bundle } = packComponent(messageQueueFolder())
  assert.ok(bundle)
  assert.deepEqual(readBundle(componentScript(bundle, 'x.strata.js')), bundle)
})

test('the JSON error locator agrees with JSON.parse on mutated manifests', () => {
  const random = createPrng(11)
  const source = messageQueueFolder()['manifest.json']
  const alphabet = '{}[]:,"\\ntrue0-.e'
  for (let n = 0; n < 2000; n++) {
    const at = random.nextU32() % source.length
    const ch = alphabet[random.nextU32() % alphabet.length]
    const mutated = random.nextU32() % 2 ? source.slice(0, at) + ch + source.slice(at) : source.slice(0, at) + source.slice(at + 1)
    let valid = true
    try { JSON.parse(mutated) } catch { valid = false }
    assert.equal(jsonErrorOffset(mutated) === -1, valid, JSON.stringify(mutated.slice(Math.max(0, at - 10), at + 10)))
  }
})
