#!/usr/bin/env node
// @ts-check
// The design token generator (task 0501, design system §15): packages/ui/tokens/tokens.json is
// the one source, and this writes tokens.css for CSS and packages/ui/src/tokens.js for canvas and
// 3D code, which cannot read CSS variables. A theme is chosen with data-theme on the root
// element, light, dark or contrast; without one, the system's colour scheme applies, and the
// contrast theme follows it too.
//
//   npm run generate:tokens
import { readFileSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import * as prettier from 'prettier'

const UI = new URL('../../packages/ui/', import.meta.url)
const SOURCE = new URL('tokens/tokens.json', UI)
const CSS_FILE = new URL('tokens/tokens.css', UI)
const JS_FILE = new URL('src/tokens.js', UI)

/**
 * @typedef {object} TokenSource
 * @property {Record<string, string>} primitives
 * @property {Record<string, string>} base
 * @property {Record<string, { size: number, line: number, weight: number, tracking?: string }>} type
 * @property {Record<string, Record<string, string>>} themes  each may `extends` another
 * @property {Record<string, string>} reducedMotion
 * @property {{ family: string, weight: number, file: string }[]} fonts
 */

/** A primitive reference, `{lapis-600}`. */
const REF = /^\{([a-z0-9-]+)\}$/

/**
 * A theme's tokens, with those of the theme it extends.
 * @param {TokenSource} source @param {string} name
 * @returns {Record<string, string>}
 */
function resolveTheme(source, name) {
  const { extends: parent, ...own } = source.themes[name]
  return { ...(parent ? resolveTheme(source, parent) : {}), ...own }
}

/** CSS declarations for tokens, with primitives as variables. @param {Record<string, string>} tokens */
const declarations = tokens =>
  Object.entries(tokens)
    .map(([key, value]) =>
      key === 'color-scheme'
        ? `color-scheme: ${value};`
        : `--st-${key}: ${value.replace(REF, 'var(--st-$1)')};`
    )
    .join('\n')

/** The typography tokens as CSS: a font shorthand, and tracking where there is some. @param {TokenSource} source */
const typeDeclarations = source =>
  Object.entries(source.type)
    .map(
      ([key, t]) =>
        `--st-type-${key}: ${t.weight} ${t.size}px/${t.line}px var(--st-font-sans);` +
        (t.tracking ? `\n--st-type-${key}-tracking: ${t.tracking};` : '')
    )
    .join('\n')

/** @param {TokenSource} source */
function css(source) {
  const theme = (/** @type {string} */ name) => declarations(resolveTheme(source, name))
  return `/* Generated by tools/tokens/generate.js from tokens.json. Do not edit it: run
 * \`npm run generate:tokens\` after changing the tokens (design system §3, §15). */
:root {
${declarations(source.primitives)}
${declarations(source.base)}
${typeDeclarations(source)}
${theme('light')}
}
:root[data-theme="dark"] {
${theme('dark')}
}
@media (prefers-color-scheme: dark) {
  :root:not([data-theme]) {
${theme('dark')}
  }
}
:root[data-theme="contrast"] {
${theme('contrast-light')}
}
@media (prefers-color-scheme: dark) {
  :root[data-theme="contrast"] {
${theme('contrast-dark')}
  }
}
@media (prefers-reduced-motion: reduce) {
  :root {
${declarations(source.reducedMotion)}
  }
}
`
}

/** @param {TokenSource} source @param {string} tokensCss */
function js(source, tokensCss) {
  /** @param {Record<string, string>} tokens */
  const values = tokens =>
    Object.fromEntries(
      Object.entries(tokens).map(([key, value]) => {
        const name = REF.exec(value)?.[1]
        return [key, name ? source.primitives[name] : value]
      })
    )
  const themes = Object.fromEntries(
    Object.keys(source.themes).map(name => [name, values(resolveTheme(source, name))])
  )
  /** @param {unknown} value */
  const frozen = value => `Object.freeze(${JSON.stringify(value)})`
  return `// @ts-check
// Generated by tools/tokens/generate.js from packages/ui/tokens/tokens.json. Do not edit it: run
// \`npm run generate:tokens\` after changing the tokens (design system §3, §15).

/**
 * Every theme's tokens, resolved to colours, lengths and shadows, for canvas and 3D code, which
 * cannot read CSS variables: light, dark, and the contrast theme in its light and dark forms.
 * @type {Readonly<Record<'light'|'dark'|'contrast-light'|'contrast-dark', Readonly<Record<string, string>>>>}
 */
export const THEMES = Object.freeze({
${Object.entries(themes)
  .map(([name, tokens]) => `${JSON.stringify(name)}: ${frozen(tokens)},`)
  .join('\n')}
})

/** The tokens every theme shares: fonts, space, sizes, strokes, radii, motion and layers. */
export const BASE = ${frozen(source.base)}

/** The typography tokens: size and line height in px, weight, and tracking where there is some. */
export const TYPE = ${frozen(source.type)}

/** What changes under prefers-reduced-motion. */
export const REDUCED_MOTION = ${frozen(source.reducedMotion)}

/** The bundled IBM Plex faces, from vendor/plex (design system §2). */
export const FONTS = ${frozen(source.fonts)}

/**
 * tokens.css, for a document or shadow root to adopt as a constructed stylesheet, since the
 * CSP of eng §16 allows no inline styles.
 */
export const TOKENS_CSS = ${JSON.stringify(tokensCss)}
`
}

/**
 * tokens.css and tokens.js for a token source, formatted as Prettier would.
 * @param {TokenSource} source
 * @returns {Promise<{ css: string, js: string }>}
 */
export async function generateTokens(source) {
  /** @param {string} text @param {URL} file */
  const format = async (text, file) => {
    const filepath = fileURLToPath(file)
    const options = await prettier.resolveConfig(filepath)
    return prettier.format(text, { ...options, filepath })
  }
  const tokensCss = await format(css(source), CSS_FILE)
  return { css: tokensCss, js: await format(js(source, tokensCss), JS_FILE) }
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  const { css: tokensCss, js: tokensJs } = await generateTokens(
    JSON.parse(readFileSync(SOURCE, 'utf8'))
  )
  writeFileSync(CSS_FILE, tokensCss)
  writeFileSync(JS_FILE, tokensJs)
  console.log('Wrote packages/ui/tokens/tokens.css and packages/ui/src/tokens.js')
}
